# Generated by Django 5.0 on 2023-12-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
